AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  PR Revisor API - Sistema asíncrono de revisión de Pull Requests con IA
  Sigue estándares arquitectónicos NBX para agentes serverless

# Parámetros estándar NBX
Parameters:
  envName:
    Type: String
    Description: Nombre del ambiente
    Default: internal
    AllowedValues:
      - internal
      - dev
      - development
      - staging
      - production
  
  NRAccountId:
    Type: String
    Description: Your New Relic account ID; necessary for distributed tracing.
    Default: "3357944"
  
  deployedVersion:
    Type: String
    Default: 1.0.0
    Description: Versión del despliegue
  
  LambdaMemory:
    Type: Number
    Default: 512
    Description: Memoria asignada a Lambda (MB)
    MinValue: 128
    MaxValue: 10240
  
  LambdaTimeout:
    Type: Number
    Default: 180
    Description: Timeout de Lambda (segundos)
  
  GitHubToken:
    Type: String
    Default: ""
    Description: GitHub Personal Access Token (se puede dejar vacío para usar desde Secrets Manager)
    NoEcho: true

# Variables globales estándar NBX
Globals:
  Function:
    Runtime: nodejs20.x
    Architectures:
      - x86_64
    Timeout: !Ref LambdaTimeout
    MemorySize: !Ref LambdaMemory
    Environment:
      Variables:
        NODE_ENV: !Ref envName
        DEPLOYED_VERSION: !Ref deployedVersion
        NODE_OPTIONS: --enable-source-maps
        LOG_LEVEL: info
        LOG_FORMAT: json
        ENABLE_REQUEST_LOGGING: true
        LOG_SAMPLE_RATE: 1.0
        POWERTOOLS_SERVICE_NAME: pr-revisor
        POWERTOOLS_METRICS_NAMESPACE: PRRevisor
        # New Relic estándar
        NEW_RELIC_ACCOUNT_ID: !Ref NRAccountId
        NEW_RELIC_TRUSTED_ACCOUNT_KEY: !Ref NRAccountId
        NEW_RELIC_EXTENSION_SEND_FUNCTION_LOGS: true
        NEW_RELIC_EXTENSION_LOG_LEVEL: DEBUG
        NEW_RELIC_SERVERLESS_MODE_ENABLED: true

Resources:
  # ================================
  # CAPAS LAMBDA
  # ================================
  AwsSdkLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub "${envName}-aws-sdk-layer"
      Description: Layer con AWS SDK v3 y dependencias básicas
      ContentUri: layers/aws-sdk-layer/
      CompatibleRuntimes:
        - nodejs20.x
      RetentionPolicy: Retain

  TreeSitterLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub "${envName}-tree-sitter-layer"
      Description: Layer con tree-sitter y tree-sitter-java para análisis de código
      ContentUri: layers/tree-sitter-layer/
      CompatibleRuntimes:
        - nodejs20.x
      RetentionPolicy: Retain

  # Usamos una layer pública oficial por ARN (no necesitamos crear la layer)
  # GitLayer se define directamente en el PRIndexerFunction usando ARN


  # ================================
  # SQS - COLAS
  # ================================
  
  # Cola para indexación (Receptor -> Indexer)
  PRIndexQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "pr-index-queue-${envName}"
      VisibilityTimeout: 3600  # 60 minutos (6x timeout de función indexer)
      MessageRetentionPeriod: 1209600  # 14 días
      ReceiveMessageWaitTimeSeconds: 20  # Long polling
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt PRIndexDLQ.Arn
        maxReceiveCount: 2

  PRIndexDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "pr-index-queue-dlq-${envName}"
      MessageRetentionPeriod: 1209600  # 14 días

  # Cola para procesamiento (Indexer -> Processor)
  PRProcessQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "pr-process-queue-${envName}"
      VisibilityTimeout: 900  # 15 minutos (5x timeout de función)
      MessageRetentionPeriod: 1209600  # 14 días
      ReceiveMessageWaitTimeSeconds: 20  # Long polling
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt PRProcessDLQ.Arn
        maxReceiveCount: 3

  # Dead Letter Queue
  PRProcessDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "pr-process-queue-dlq-${envName}"
      MessageRetentionPeriod: 1209600  # 14 días

  # ================================
  # S3 - BUCKET DE ÍNDICES
  # ================================
  DependencyIndexBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "dependency-indices-${envName}-${AWS::AccountId}"
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldIndices
            Status: Enabled
            ExpirationInDays: 90
            NoncurrentVersionExpirationInDays: 30

  # ================================
  # S3 - BUCKET DE ARTEFACTOS PR
  # ================================
  PRArtefactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "pr-artefacts-${envName}-${AWS::AccountId}"
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldArtefacts
            Status: Enabled
            ExpirationInDays: 30
            NoncurrentVersionExpirationInDays: 7

  # ================================
  # API GATEWAY
  # ================================
  PRRevisorApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "${envName}-pr-revisor-api"
      StageName: !Ref envName
      Cors:
        AllowMethods: "'POST, OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Hub-Signature-256'"
        AllowOrigin: "'*'"

  # ================================
  # FUNCIÓN LAMBDA - INDEXER
  # ================================
  PRIndexerFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - index.ts
        Target: es2020
        Sourcemap: true
        External:
          - '@aws-sdk/*'
          - '@aws-lambda-powertools/*'
          - 'tree-sitter'
          - 'tree-sitter-java'
          - 'uuid'
    Properties:
      FunctionName: !Join ["-", [!Ref envName, "nbx", "pr-indexer", "lambda"]]
      CodeUri: src/pr-indexer/
      Handler: index.handler
      Timeout: 600  # 10 minutos para clonar y indexar
      MemorySize: 2048  # Más memoria para operaciones Git y indexing
      Layers:
        - !Ref AwsSdkLayer
        - !Ref TreeSitterLayer
        # Layer oficial de LambCI para Git (ampliamente usado en la comunidad)
        - arn:aws:lambda:us-east-1:553035198032:layer:git-lambda2:8
        # # Layer de New Relic para monitoreo (deshabilitado temporalmente)
        # - arn:aws:lambda:us-east-1:451483290750:layer:NewRelicNodeJS20X:8
      Environment:
        Variables:
          # NEW_RELIC_LAMBDA_HANDLER: index.handler
          # Variables de aplicación
          PR_ARTIFACTS_BUCKET: !Ref PRArtefactsBucket
          PR_PROCESS_QUEUE_URL: !Ref PRProcessQueue
          REQUEST_ID_HEADER: x-request-id
          GITHUB_TOKEN: !Ref GitHubToken
          # Git config
          GIT_CONFIG_GLOBAL: /tmp/.gitconfig
          GIT_CONFIG_NOGLOBAL: true
          PATH: "/opt/bin:/usr/local/bin:/usr/bin:/bin"
      Policies:
        # Política para obtener licencia de New Relic
        # # Política para obtener licencia de New Relic (deshabilitado temporalmente)
        # - AWSSecretsManagerGetSecretValuePolicy:
        #     SecretArn: !ImportValue NewRelicLicenseKeySecret-NewRelic-LicenseKeySecretARN
        # Permisos S3 para subir artefactos
        - S3CrudPolicy:
            BucketName: !Ref PRArtefactsBucket
        # Permisos SQS para enviar mensajes
        - SQSSendMessagePolicy:
            QueueName: !GetAtt PRProcessQueue.QueueName
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt PRIndexQueue.Arn
            BatchSize: 1

  # ================================
  # FUNCIÓN LAMBDA - RECEPTOR
  # ================================
  PRReceptorFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - index.ts
        Target: es2020
        Sourcemap: true
        External:
          - '@aws-sdk/*'
          - '@aws-lambda-powertools/*'
          - 'uuid'
    Properties:
      FunctionName: !Join ["-", [!Ref envName, "nbx", "pr-receptor", "lambda"]]
      CodeUri: src/pr-receptor/
      Handler: index.handler
      Layers:
        - !Ref AwsSdkLayer
      Environment:
        Variables:
          PR_INDEX_QUEUE_URL: !Ref PRIndexQueue
          REQUEST_ID_HEADER: x-request-id
          GITHUB_TOKEN: !Ref GitHubToken
      Policies:
        # Permisos SQS para enviar mensajes a la cola de indexación
        - SQSSendMessagePolicy:
            QueueName: !GetAtt PRIndexQueue.QueueName
      Events:
        PRWebhook:
          Type: Api
          Properties:
            RestApiId: !Ref PRRevisorApi
            Path: /webhook
            Method: POST

  # ================================
  # FUNCIÓN LAMBDA - PROCESADOR
  # ================================
  PRProcessorFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - index.ts
        Target: es2020
        Sourcemap: true
        External:
          - '@aws-sdk/*'
          - '@aws-lambda-powertools/*'
          - 'tree-sitter'
          - 'tree-sitter-java'
          - 'uuid'
    Properties:
      FunctionName: !Join ["-", [!Ref envName, "nbx", "pr-processor", "lambda"]]
      CodeUri: src/pr-processor/
      Handler: index.handler
      Timeout: 900  # 15 minutos para procesamiento IA
      MemorySize: 1024  # Más memoria para procesamiento
      Layers:
        - !Ref AwsSdkLayer
        # TODO: Re-habilitar New Relic cuando sea compatible con ES Modules
        # - arn:aws:lambda:us-east-1:451483290750:layer:NewRelicNodeJS20X:8
      Environment:
        Variables:
          # NEW_RELIC_LAMBDA_HANDLER: app.lambdaHandler
          # Variables de aplicación
          PR_PROCESS_QUEUE_URL: !Ref PRProcessQueue
          DEPENDENCY_INDEX_BUCKET: !Ref DependencyIndexBucket
          PR_ARTIFACTS_BUCKET: !Ref PRArtefactsBucket
          ENABLE_DEPENDENCY_ANALYSIS: true
          GITHUB_TOKEN: !Ref GitHubToken
      Policies:
        # Política para obtener licencia de New Relic
        # # Política para obtener licencia de New Relic (deshabilitado temporalmente)
        # - AWSSecretsManagerGetSecretValuePolicy:
        #     SecretArn: !ImportValue NewRelicLicenseKeySecret-NewRelic-LicenseKeySecretARN
        # Permisos S3 para leer índices de dependencias
        - S3ReadPolicy:
            BucketName: !Ref DependencyIndexBucket
        # Permisos S3 para leer artefactos de PR
        - S3ReadPolicy:
            BucketName: !Ref PRArtefactsBucket
        # Permisos Bedrock (para la fase 3)
        - Statement:
          - Effect: Allow
            Action:
              - bedrock:InvokeModel
              - bedrock:InvokeModelWithResponseStream
            Resource: 
              - !Sub "arn:aws:bedrock:${AWS::Region}::foundation-model/us.anthropic.claude-sonnet-4-20250514-v1:0"
      Events:
        ProcessQueue:
          Type: SQS
          Properties:
            Queue: !GetAtt PRProcessQueue.Arn
            BatchSize: 1  # Procesar de a uno por la complejidad
            FunctionResponseTypes:
              - ReportBatchItemFailures

# ================================
# OUTPUTS
# ================================
Outputs:
  WebhookUrl:
    Description: "URL del API Gateway para webhooks de GitHub"
    Value: !Sub "https://${PRRevisorApi}.execute-api.${AWS::Region}.amazonaws.com/${envName}/webhook"
    Export:
      Name: !Sub "${AWS::StackName}-WebhookUrl"
  
  PRProcessQueueUrl:
    Description: "URL de la cola SQS de procesamiento"
    Value: !Ref PRProcessQueue
    Export:
      Name: !Sub "${AWS::StackName}-ProcessQueue"
  
  PRArtefactsBucketName:
    Description: "Nombre del bucket S3 para artefactos de PR"
    Value: !Ref PRArtefactsBucket
    Export:
      Name: !Sub "${AWS::StackName}-ArtefactsBucket"